# Build Wget2

name: Build Wget2 b1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    #container: github.com/Jeffery186/docker-ubuntu-mingw:main
    steps:
      - name: Installation depends

        run: |


          apt-get update
          apt-get upgrade 
          apt-get install -y make gcc libc-dev mingw-w64 liblzma-dev
      - uses: actions/checkout@v2
      - name: Build
        run: |
          chmod +x build.sh
          /bin/bash ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: wget2
          path: /usr/local/x86_64-w64-mingw32/bin/
